version: '3'

services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "movierank"
    ports:
      - "5433:5432"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}